### ISSUE TITLE
convert dashes to underscores

### ISSUE THREAD

**Issue by jaredmoody** [tpitale/constant_cache#2]
Just a small thing that would be nice:

I'm using my model slugs as the key to caches_constants. Since the url friendly slug often has a dash in it, e.g. "pending-account", it would be nice if this got converted to PENDING_ACCOUNT rather than PENDINGACCOUNT.

This could be accomplished by changing line 11 of core_ext.rb to the following:

``` ruby
value = self.strip.gsub(/\s|-+/, '_').gsub(/[^\w_]/, '').gsub(/_{2,}/, '_').upcase
```

What do you think?

**Comment by tpitale** [comment]
If you send a PR I'll happily merge it in. Or, gimme a few days and I'll have some time to get to it. Thanks!

**Comment by jaredmoody** [comment]
PR sent :)
